### ISSUE TITLE
Last frame freeze on MAV 8

### ISSUE THREAD

**Issue by TondaKrist** [krzyc/CasparCG-Server#2]
Last frame freezes for 5-10 frames before background clip is started.

**Comment by krzyc** [comment]
Can you test it in 2.1.0b1_MAV_9? How to reproduce it?

**Comment by krzyc** [comment]
Closing - no feedback.

**Comment by TondaKrist** [comment]
I would like to open that issue again, since in MAV9 is not last frame freeze, but there is a problem with audio sync. Maybe it is easier to fix last frame freeze than audio sync. If I put for example clip into loop, you can see that there is a last frame freeze. there is a demo file: http://download.satplus.cz/PUBLIC/JingleTenis.mpg
