### ISSUE TITLE
Building MAV9 on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by NL5L** [krzyc/CasparCG-Server#4]
Hello krzyc,

since we can not send (private) messages, I will try it this way. I am a long time CasparCG User and I like your contributions to MAV very much! While I almost never build CasparCG myself (I rather use the builds from builds.casparcg.com) with the build-scripts it was very easy.

But now with Ubuntu 16.04 it looks like it is broken, but since you also build your MAV 9 for U16.10 I hope you could tell me what I am doing wrong....

I just follow the directives in the BUILDING file with the following result:
#### ----------------------------------
user@CasparCGdemo:~/Git/20161208/CasparCG-Server/build-scripts$ ./set-variables-and-build-linux.sh 
cef/bin/linux/libcef.so
Cleaning...
Running cmake...
CMake Error at CMakeLists.txt:2 (project):
  Generator
    Unix Makefiles
  does not support platform specification, but platform
    x64
  was specified.

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/user/Git/20161208/CasparCG-Server/build/CMakeFiles/CMakeOutput.log".
cmake failed
#### ----------------------------------

The log is almost empty: The system is: Linux - 4.4.0-53-generic - x86_64

The error will be a little less when I use:
cmake -G "Unix Makefiles" -A x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..

#### ----------------------------------
gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
CMake Error at CMakeLists.txt:2 (project):
  Generator
    Unix Makefiles
  does not support platform specification, but platform
    x64
  was specified.

-- Configuring incomplete, errors occurred!
See also "/home/user/Git/20161208/CasparCG-Server/build-scripts/CMakeFiles/CMakeOutput.log".
#### ----------------------------------

Hopefully you can help me get MAV 9 running on my fresh Ubuntu 16.04 LTS system.

Kind regards,
Ed

**Comment by krzyc** [comment]
I was not using these scripts, but tried it now, and error was same.
"Unix Makefiles does not support platform specification, but platform x64 was specified".
Try cmake without "-A x64" option - it works for me.

**Comment by krzyc** [comment]
I have proposed a change to main repository: https://github.com/CasparCG/Server/pull/519

**Comment by NL5L** [comment]
haha thanks !! You helped me a lot...
I also tried to delete the "-A x64" but I did not clear my cache.. :-(

Super ! The MAV 9 version is building right now...

**Comment by TondaKrist** [comment]
Hi if you are building new version, is it possible please add this fix: https://github.com/CasparCG/Server/issues/515

there is a zero division

So it should fix problem of not returning INFO if video is loaded in background.
Thanks a lot

**Comment by krzyc** [comment]
@TondaKrist Here is compiled linux binary built from current source tree with patch mentioned above applied:
https://github.com/krzyc/CasparCG-Server/releases/download/2.1.0b1_MAV_9/casparcg.patch1.bz2
But I am not sure if this is proper way of fixing this upstream bug and do not want to examine it right now.

**Comment by TondaKrist** [comment]
Thanks a lot, I really really appriciate it, but I am running on Windows. Would you be sooo nice and do a patch for Win? Last freeze frame "bug" is OK on MAV9.

**Comment by krzyc** [comment]
No problem - here it is (just updated exe): https://github.com/krzyc/CasparCG-Server/releases/download/2.1.0b1_MAV_9/casparcg.w64.patch2.zip
I tought that you are using linux because of topic.

**Comment by TondaKrist** [comment]
Great, works like a charm! Thank you very much, is there a way how to contribute your build? :) Unfortunately a have to start a new issue
