### ISSUE TITLE
Encode/Export captured material

### ISSUE THREAD

**Issue by Sidonai-1** [krzyc/CasparCG-Server#9]
Right now you can only use the .mav material with the Caspar Mav Server itself.

We should be able to convert the .mav files into any other format using, for example, ffmpeg.

When trying that, it doesn't generate valid video files, most skip frames dramatically, sometimes it does not show any image at all.

Mav10 shows a slightly better behaviour about this than Mav9, but there are still some errors.

**Comment by krzyc** [comment]
Replay module uses custom file format. Here is a diff with quick and dirty demuxer for ffmpeg:
https://github.com/krzyc/FFmpeg/commit/01c1ddb80eda853d207a5c59f04d382cb5e839d5
